from setuptools import setup, find_packages

setup(
    name="aiops_sdk",
    version="0.2.0",
    packages=find_packages(),
    install_requires=[],
    extras_require={
        "openai": ["openai>=1.0.0"],
        "anthropic": ["anthropic>=0.18.0"],
        "langchain": ["langchain-core>=0.1.0"],
        "llamaindex": ["llama-index-core>=0.10.0"],
        "crewai": ["crewai>=0.30.0"],
        "autogen": ["pyautogen>=0.2.0"],
        "local": ["requests>=2.28.0"],
        "all": [
            "openai>=1.0.0",
            "anthropic>=0.18.0",
            "langchain-core>=0.1.0",
            "llama-index-core>=0.10.0",
            "crewai>=0.30.0",
            "pyautogen>=0.2.0",
            "requests>=2.28.0",
        ],
    },
    description="Python SDK for AIOps Platform Telemetry Ingestion",
    long_description="Auto-instrumentation SDK supporting OpenAI, Anthropic, LangChain, LlamaIndex, CrewAI, AutoGen, and local model providers (Ollama, vLLM, HuggingFace).",
    author="AIOps Team",
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
)
